[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "i686-kernel.json"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
